/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Conexion.ConectarBD;
import Controlador.ListarProducto;
import static Vista.InterfazAdministrarProducto.codProdutoLista;
import static Vista.InterfazAdministrarProducto.conexion;
import static Vista.InterfazAdministrarProducto.jLabelFoto;
import static Vista.InterfazAdministrarProducto.jLabelMarca;
import static Vista.InterfazAdministrarProducto.jLabelModelo;
import static Vista.InterfazAdministrarProducto.jPanelAdministrarProducto;
import static Vista.InterfazAdministrarProducto.offset;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.border.EmptyBorder;
import javax.swing.table.TableRowSorter;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class InterfazBuscarProductoo extends javax.swing.JFrame {
    DefaultTableModel dtm=new DefaultTableModel ();
    
     static Connection conexion=null;
    ConectarBD con = new ConectarBD();
    Color twhite=new Color(255,255,255,128);
    Color newColor=new Color(195,224,229,240);
    public static javax.swing.JLabel jLabelFoto;
    public static javax.swing.JLabel jLabelMarca;
    public static javax.swing.JLabel jLabelModelo;
    public static int [] codProdutoLista=new int [10];
    public static javax.swing.JButton bProdEditar;
    public static javax.swing.JButton bProdEliminar;
    public static javax.swing.JButton bProdRegistrar;
    public static int codigoNumero;
    ListarProducto listaproducto=new ListarProducto();
    public static int offset=0;
    Border border= BorderFactory.createLineBorder(twhite,4);
    Border border2= BorderFactory.createLineBorder(newColor,4);
    //Border border= BorderFactory.createLineBorder(Color.red,1);
    //Border border=BorderFactory.createLoweredBevelBorder();
     /*Border lineBorder = BorderFactory.createLineBorder(Color.GRAY);
        Border emptyBorder = new EmptyBorder(0, 10, 0, 10); // add some padding
        Border roundedBorder = BorderFactory.createEmptyBorder(0, 5, 0, 5);*/
        
        
        
    int cantidadElementos;
    private javax.swing.JLabel ultimoMarcado;
   
    /**
     * Creates new form InterfazBuscarProductoo
     */
    public InterfazBuscarProductoo() {
        initComponents();
        String[] Titulo= new String [] {"ID", "Marca", "Modelo", "Precio", "Descripcion", "fotografia"};
  dtm.setColumnIdentifiers(Titulo);
  
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonbuscar = new javax.swing.JButton();
        botonanadir = new javax.swing.JButton();
        botonIzquierda = new javax.swing.JButton();
        botonderecha = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 77, 116));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbuscarActionPerformed(evt);
            }
        });
        textbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textbuscarKeyTyped(evt);
            }
        });
        jPanel1.add(textbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 102, 250, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modelo de Producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUSCAR PRODUCTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        botonbuscar.setBackground(new java.awt.Color(0, 102, 153));
        botonbuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/searchSmall.png"))); // NOI18N
        botonbuscar.setText("BUSCAR");
        botonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 130, 30));

        botonanadir.setBackground(new java.awt.Color(0, 102, 153));
        botonanadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/addSmall.png"))); // NOI18N
        botonanadir.setText("AÑADIR");
        botonanadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonanadirActionPerformed(evt);
            }
        });
        jPanel1.add(botonanadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, 130, 30));

        botonIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/izquierda.png"))); // NOI18N
        botonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdaActionPerformed(evt);
            }
        });
        jPanel1.add(botonIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        botonderecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/derecha.png"))); // NOI18N
        jPanel1.add(botonderecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/INICIO (2).png"))); // NOI18N
        home.setText("HOME");
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 40));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, 70, 100));

        jLabel4.setText("jLabel3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, 100));

        jLabel5.setText("jLabel3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 70, 100));

        jLabel6.setText("jLabel3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 70, 100));

        jLabel7.setText("jLabel3");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 70, 100));

        jLabel8.setText("jLabel3");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 70, 100));

        jLabel9.setText("jLabel3");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 70, 100));

        jLabel10.setText("jLabel3");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 70, 100));

        jLabel11.setText("jLabel3");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 70, 100));

        jLabel12.setText("jLabel3");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 70, 100));

        jLabel13.setText("jLabel3");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 70, 100));

        jLabel14.setText("jLabel3");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 70, 100));

        jLabel15.setText("jLabel3");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 70, 100));

        jLabel16.setText("jLabel3");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 70, 100));

        jLabel17.setText("jLabel3");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 70, 100));

        jLabel18.setText("jLabel3");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 70, 100));

        jLabel19.setText("jLabel3");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 70, 100));

        jLabel20.setText("jLabel3");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 70, 100));

        jLabel21.setText("jLabel3");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 70, 100));

        jLabel22.setText("jLabel3");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 70, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbuscarActionPerformed
            

        // TODO add your handling code here:
    }//GEN-LAST:event_textbuscarActionPerformed
    
    private void botonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonbuscarActionPerformed
            if(textbuscar.getText().equals("")){            
            offset=0;         
        }
           


        // TODO add your handling code here:
    }//GEN-LAST:event_botonbuscarActionPerformed

    private void botonanadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonanadirActionPerformed
    
        
// TODO add your handling code here:
    }//GEN-LAST:event_botonanadirActionPerformed

    private void textbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textbuscarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textbuscarKeyTyped

    private void botonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdaActionPerformed
        offset=offset-10;
        if(offset==0){
            botonIzquierda.setEnabled(false);
        }
        botonderecha.setEnabled(true);
        listaproducto.paginarFotoInicio(jLabelFoto, jLabelMarca, jLabelModelo, jPanelAdministrarProducto, codProdutoLista,offset);
        botonanadir.setEnabled(false);
        
        ultimoMarcado.setBorder(null);   
    }//GEN-LAST:event_botonIzquierdaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazBuscarProductoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazBuscarProductoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazBuscarProductoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazBuscarProductoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazBuscarProductoo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIzquierda;
    private javax.swing.JButton botonanadir;
    private javax.swing.JButton botonbuscar;
    private javax.swing.JButton botonderecha;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textbuscar;
    // End of variables declaration//GEN-END:variables
}
