/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Conexion.ConectarBD;
import Controlador.ListarProducto;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.BorderFactory;
import javax.swing.border.Border;


/**
 *
 * @author PC
 */
public class InterfazAdministrarProducto extends javax.swing.JFrame {
    static Connection conexion=null;
    ConectarBD con = new ConectarBD();
    Color twhite=new Color(255,255,255,128);
    Color newColor=new Color(195,224,229,240);
    public static javax.swing.JLabel jLabelFoto;
    public static javax.swing.JLabel jLabelMarca;
    public static javax.swing.JLabel jLabelModelo;
    public static int [] codProdutoLista=new int [10];
    public static javax.swing.JButton bProdEditar;
    public static javax.swing.JButton bProdEliminar;
    public static javax.swing.JButton bProdRegistrar;
    public static int codigoNumero;
    ListarProducto listaImagenes=new ListarProducto();
    public static int offset=0;
    Border border= BorderFactory.createLineBorder(twhite,4);
    Border border2= BorderFactory.createLineBorder(newColor,4);
    //Border border= BorderFactory.createLineBorder(Color.red,1);
    //Border border=BorderFactory.createLoweredBevelBorder();
    private javax.swing.JLabel ultimoMarcado;
    public InterfazAdministrarProducto() {
        initComponents();
        bProdEditar=jButtonEditar;
        bProdEliminar=jButtonEliminar;
        bProdRegistrar=jButtonRegistrar;
        ultimoMarcado=jLabelMark1;
        listaImagenes.mostrarFotoInicio(jLabelFoto, jLabelMarca, jLabelModelo, jPanelAdministrarProducto, codProdutoLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAdministrarProducto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBuscarCoincidencia = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabelHover1 = new javax.swing.JLabel();
        jLabelHover2 = new javax.swing.JLabel();
        jLabelHover3 = new javax.swing.JLabel();
        jLabelHover4 = new javax.swing.JLabel();
        jLabelHover5 = new javax.swing.JLabel();
        jLabelHover6 = new javax.swing.JLabel();
        jLabelHover7 = new javax.swing.JLabel();
        jLabelHover8 = new javax.swing.JLabel();
        jLabelHover9 = new javax.swing.JLabel();
        jLabelHover10 = new javax.swing.JLabel();
        jLabelMark1 = new javax.swing.JLabel();
        jLabelMark2 = new javax.swing.JLabel();
        jLabelMark3 = new javax.swing.JLabel();
        jLabelMark4 = new javax.swing.JLabel();
        jLabelMark5 = new javax.swing.JLabel();
        jLabelMark6 = new javax.swing.JLabel();
        jLabelMark7 = new javax.swing.JLabel();
        jLabelMark8 = new javax.swing.JLabel();
        jLabelMark9 = new javax.swing.JLabel();
        jLabelMark10 = new javax.swing.JLabel();
        jLabelFoto1 = new javax.swing.JLabel();
        jLabelMarcaFoto1 = new javax.swing.JLabel();
        jLabelModeloFoto1 = new javax.swing.JLabel();
        jLabelFoto2 = new javax.swing.JLabel();
        jLabelMarcaFoto2 = new javax.swing.JLabel();
        jLabelModeloFoto2 = new javax.swing.JLabel();
        jLabelFoto3 = new javax.swing.JLabel();
        jLabelMarcaFoto3 = new javax.swing.JLabel();
        jLabelModeloFoto3 = new javax.swing.JLabel();
        jLabelFoto4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelFoto5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelFoto6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelFoto7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelFoto8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelFoto9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelFoto10 = new javax.swing.JLabel();
        jLabelMarcaFoto10 = new javax.swing.JLabel();
        jLabelModeloFoto10 = new javax.swing.JLabel();
        jButtonIzquierda = new javax.swing.JButton();
        jButtonDerecha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelAdministrarProducto.setBackground(new java.awt.Color(37, 77, 116));
        jPanelAdministrarProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMINISTRAR PRODUCTO");
        jPanelAdministrarProducto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jTextFieldBuscarCoincidencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextFieldBuscarCoincidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarCoincidenciaActionPerformed(evt);
            }
        });
        jTextFieldBuscarCoincidencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarCoincidenciaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarCoincidenciaKeyTyped(evt);
            }
        });
        jPanelAdministrarProducto.add(jTextFieldBuscarCoincidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 260, 30));

        jButtonBuscar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
        });
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jButtonBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonBuscarKeyPressed(evt);
            }
        });
        jPanelAdministrarProducto.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de Producto");
        jPanelAdministrarProducto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 210, -1));

        jButtonEditar.setBackground(new java.awt.Color(95, 143, 169));
        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanelAdministrarProducto.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, -1, 30));

        jButtonEliminar.setBackground(new java.awt.Color(95, 143, 169));
        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanelAdministrarProducto.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, -1, 30));

        jButtonRegistrar.setBackground(new java.awt.Color(95, 143, 169));
        jButtonRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jPanelAdministrarProducto.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 610, -1, 30));

        jButtonHome.setText("home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanelAdministrarProducto.add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabelHover1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabelHover1FocusGained(evt);
            }
        });
        jLabelHover1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHover1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHover1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHover1MouseExited(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, 160));

        jLabelHover2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHover2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHover2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHover2MouseExited(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 140, 160));

        jLabelHover3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHover3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHover3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHover3MouseExited(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelHover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 140, 160));

        jLabelHover4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHover4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHover4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHover4MouseExited(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelHover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 140, 160));

        jLabelHover5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHover5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHover5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHover5MouseExited(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelHover5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 140, 160));

        jLabelHover6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHover6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHover6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHover6MouseExited(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelHover6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 140, 160));

        jLabelHover7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHover7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHover7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHover7MouseExited(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelHover7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 140, 160));

        jLabelHover8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHover8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHover8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHover8MouseExited(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelHover8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 140, 160));

        jLabelHover9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHover9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHover9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHover9MouseExited(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelHover9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 140, 160));

        jLabelHover10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHover10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHover10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHover10MouseExited(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelHover10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 140, 160));

        jLabelMark1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabelMark1FocusGained(evt);
            }
        });
        jLabelMark1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMark1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMark1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMark1MouseExited(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelMark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, 160));
        jPanelAdministrarProducto.add(jLabelMark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 140, 160));
        jPanelAdministrarProducto.add(jLabelMark3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 140, 160));
        jPanelAdministrarProducto.add(jLabelMark4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 140, 160));
        jPanelAdministrarProducto.add(jLabelMark5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 140, 160));
        jPanelAdministrarProducto.add(jLabelMark6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 140, 160));
        jPanelAdministrarProducto.add(jLabelMark7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 140, 160));
        jPanelAdministrarProducto.add(jLabelMark8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 140, 160));
        jPanelAdministrarProducto.add(jLabelMark9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 140, 160));
        jPanelAdministrarProducto.add(jLabelMark10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 140, 160));

        jLabelFoto1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto1.setName(""); // NOI18N
        jLabelFoto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFoto1MouseClicked(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, 110));

        jLabelMarcaFoto1.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelMarcaFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 110, -1));

        jLabelModeloFoto1.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelModeloFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabelFoto2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFoto2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelFoto2MouseEntered(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 140, 110));

        jLabelMarcaFoto2.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelMarcaFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jLabelModeloFoto2.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelModeloFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        jLabelFoto3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFoto3MouseClicked(evt);
            }
        });
        jPanelAdministrarProducto.add(jLabelFoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 140, 110));

        jLabelMarcaFoto3.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelMarcaFoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        jLabelModeloFoto3.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelModeloFoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        jLabelFoto4.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelFoto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 140, 110));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        jLabelFoto5.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFoto5.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelFoto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 140, 110));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, -1, -1));

        jLabelFoto6.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelFoto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 140, 110));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));

        jLabelFoto7.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelFoto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 140, 110));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        jLabelFoto8.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelFoto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 140, 110));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, -1, -1));

        jLabelFoto9.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelFoto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 140, 110));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));

        jLabelFoto10.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelFoto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 140, 110));

        jLabelMarcaFoto10.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelMarcaFoto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, -1, -1));

        jLabelModeloFoto10.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAdministrarProducto.add(jLabelModeloFoto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, -1, -1));

        jButtonIzquierda.setText("left");
        jButtonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzquierdaActionPerformed(evt);
            }
        });
        jPanelAdministrarProducto.add(jButtonIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, -1, -1));

        jButtonDerecha.setText("right");
        jButtonDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDerechaActionPerformed(evt);
            }
        });
        jPanelAdministrarProducto.add(jButtonDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdministrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAdministrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarCoincidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarCoincidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarCoincidenciaActionPerformed

    private void jTextFieldBuscarCoincidenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarCoincidenciaKeyPressed

    }//GEN-LAST:event_jTextFieldBuscarCoincidenciaKeyPressed

    private void jTextFieldBuscarCoincidenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarCoincidenciaKeyTyped

    }//GEN-LAST:event_jTextFieldBuscarCoincidenciaKeyTyped

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked

    }//GEN-LAST:event_jButtonBuscarMouseClicked

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        //listaImagenes.limpiarFotoInicio(jLabelFoto, jLabelMarca, jLabelModelo, jPanelAdministrarProducto);
        listaImagenes.buscarImagenInicio(jLabelFoto, jLabelMarca, jLabelModelo, jPanelAdministrarProducto, codProdutoLista, jTextFieldBuscarCoincidencia.getText());
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonBuscarKeyPressed

    }//GEN-LAST:event_jButtonBuscarKeyPressed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        InterfazEditarProducto editarPro=new InterfazEditarProducto();
        editarPro.setVisible(true);
        editarPro.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        InterfazEliminarProducto eliminarPro=new InterfazEliminarProducto();
        eliminarPro.setVisible(true);
        eliminarPro.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        InterfazRegistrarProducto registrarPro=new InterfazRegistrarProducto();
        registrarPro.setVisible(true);
        registrarPro.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jLabelFoto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFoto1MouseClicked
        
    }//GEN-LAST:event_jLabelFoto1MouseClicked

    private void jLabelFoto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFoto2MouseClicked
        
    }//GEN-LAST:event_jLabelFoto2MouseClicked

    private void jLabelFoto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFoto3MouseClicked
        
    }//GEN-LAST:event_jLabelFoto3MouseClicked

    private void jButtonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzquierdaActionPerformed
        offset=offset-10;
        listaImagenes.paginarFotoInicio(jLabelFoto, jLabelMarca, jLabelModelo, jPanelAdministrarProducto, codProdutoLista,offset);
    }//GEN-LAST:event_jButtonIzquierdaActionPerformed

    private void jButtonDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDerechaActionPerformed
        offset=offset+10;
        //listaImagenes.limpiarFotoInicio(jLabelFoto, jLabelMarca, jLabelModelo, jPanelAdministrarProducto);
        listaImagenes.paginarFotoInicio(jLabelFoto, jLabelMarca, jLabelModelo, jPanelAdministrarProducto, codProdutoLista,offset);
    }//GEN-LAST:event_jButtonDerechaActionPerformed

    private void jLabelHover1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover1MouseEntered
        if(jLabelFoto1.getIcon()!=null){
            jLabelHover1.setBorder(border);
        }
        
    }//GEN-LAST:event_jLabelHover1MouseEntered

    private void jLabelHover1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabelHover1FocusGained
        
    }//GEN-LAST:event_jLabelHover1FocusGained

    private void jLabelHover1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover1MouseClicked
        ultimoMarcado.setBorder(null);
        if(jLabelFoto1.getIcon()!=null){
            codigoNumero=codProdutoLista[0];
            jLabelMark1.setBorder(border2);
            ultimoMarcado=jLabelMark1;
        }        
    }//GEN-LAST:event_jLabelHover1MouseClicked

    private void jLabelHover1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover1MouseExited
        jLabelHover1.setBorder(null);        
    }//GEN-LAST:event_jLabelHover1MouseExited

    private void jLabelFoto2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFoto2MouseEntered
        
    }//GEN-LAST:event_jLabelFoto2MouseEntered

    private void jLabelHover2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover2MouseEntered
        if(jLabelFoto2.getIcon()!=null){
            jLabelHover2.setBorder(border);
        }
        
    }//GEN-LAST:event_jLabelHover2MouseEntered

    private void jLabelHover3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover3MouseEntered
        if(jLabelFoto3.getIcon()!=null){
            jLabelHover3.setBorder(border);
        }
        
    }//GEN-LAST:event_jLabelHover3MouseEntered

    private void jLabelHover4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover4MouseEntered
        if(jLabelFoto4.getIcon()!=null){
            jLabelHover4.setBorder(border);
        }
        
    }//GEN-LAST:event_jLabelHover4MouseEntered

    private void jLabelHover5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover5MouseEntered
        if(jLabelFoto5.getIcon()!=null){
            jLabelHover5.setBorder(border);
        }
        
    }//GEN-LAST:event_jLabelHover5MouseEntered

    private void jLabelHover6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover6MouseEntered
        if(jLabelFoto6.getIcon()!=null){
            jLabelHover6.setBorder(border);
        }
        
    }//GEN-LAST:event_jLabelHover6MouseEntered

    private void jLabelHover7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover7MouseEntered
        if(jLabelFoto7.getIcon()!=null){
            jLabelHover7.setBorder(border);
        }        
    }//GEN-LAST:event_jLabelHover7MouseEntered

    private void jLabelHover8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover8MouseEntered
        if(jLabelFoto8.getIcon()!=null){
            jLabelHover8.setBorder(border);
        }
    }//GEN-LAST:event_jLabelHover8MouseEntered

    private void jLabelHover9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover9MouseEntered
        if(jLabelFoto9.getIcon()!=null){
            jLabelHover9.setBorder(border);
        }
    }//GEN-LAST:event_jLabelHover9MouseEntered

    private void jLabelHover10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover10MouseEntered
        if(jLabelFoto10.getIcon()!=null){
            jLabelHover10.setBorder(border);
        }
    }//GEN-LAST:event_jLabelHover10MouseEntered

    private void jLabelHover2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover2MouseExited
        jLabelHover2.setBorder(null);
    }//GEN-LAST:event_jLabelHover2MouseExited

    private void jLabelHover3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover3MouseExited
        jLabelHover3.setBorder(null);
    }//GEN-LAST:event_jLabelHover3MouseExited

    private void jLabelHover4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover4MouseExited
        jLabelHover4.setBorder(null);
    }//GEN-LAST:event_jLabelHover4MouseExited

    private void jLabelHover5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover5MouseExited
        jLabelHover5.setBorder(null);
    }//GEN-LAST:event_jLabelHover5MouseExited

    private void jLabelHover6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover6MouseExited
        jLabelHover6.setBorder(null);
    }//GEN-LAST:event_jLabelHover6MouseExited

    private void jLabelHover7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover7MouseExited
        jLabelHover7.setBorder(null);
    }//GEN-LAST:event_jLabelHover7MouseExited

    private void jLabelHover8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover8MouseExited
        jLabelHover8.setBorder(null);
    }//GEN-LAST:event_jLabelHover8MouseExited

    private void jLabelHover9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover9MouseExited
        jLabelHover9.setBorder(null);
    }//GEN-LAST:event_jLabelHover9MouseExited

    private void jLabelHover10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover10MouseExited
        jLabelHover10.setBorder(null);
    }//GEN-LAST:event_jLabelHover10MouseExited

    private void jLabelHover2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover2MouseClicked
        ultimoMarcado.setBorder(null);
        if(jLabelFoto2.getIcon()!=null){
            codigoNumero=codProdutoLista[1];
            jLabelMark2.setBorder(border2);
            ultimoMarcado=jLabelMark2;
        }
        
    }//GEN-LAST:event_jLabelHover2MouseClicked

    private void jLabelHover3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover3MouseClicked
        ultimoMarcado.setBorder(null);
        if(jLabelFoto3.getIcon()!=null){
            codigoNumero=codProdutoLista[2];
            jLabelMark3.setBorder(border2);
            ultimoMarcado=jLabelMark3;
        }
        
    }//GEN-LAST:event_jLabelHover3MouseClicked

    private void jLabelHover4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover4MouseClicked
        ultimoMarcado.setBorder(null);
        if(jLabelFoto4.getIcon()!=null){
            codigoNumero=codProdutoLista[3];
            jLabelMark4.setBorder(border2);
            ultimoMarcado=jLabelMark4;
        }
        
    }//GEN-LAST:event_jLabelHover4MouseClicked

    private void jLabelHover5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover5MouseClicked
        ultimoMarcado.setBorder(null);
        if(jLabelFoto5.getIcon()!=null){
            codigoNumero=codProdutoLista[4];
            jLabelMark5.setBorder(border2);
            ultimoMarcado=jLabelMark5;
        }
        
    }//GEN-LAST:event_jLabelHover5MouseClicked

    private void jLabelHover6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover6MouseClicked
        ultimoMarcado.setBorder(null);
        if(jLabelFoto6.getIcon()!=null){
            codigoNumero=codProdutoLista[5];
            jLabelMark6.setBorder(border2);
            ultimoMarcado=jLabelMark6;
        }
        
    }//GEN-LAST:event_jLabelHover6MouseClicked

    private void jLabelHover7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover7MouseClicked
        ultimoMarcado.setBorder(null);
        if(jLabelFoto7.getIcon()!=null){
            codigoNumero=codProdutoLista[6];
            jLabelMark7.setBorder(border2);
            ultimoMarcado=jLabelMark7;
        }
        
    }//GEN-LAST:event_jLabelHover7MouseClicked

    private void jLabelHover8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover8MouseClicked
        ultimoMarcado.setBorder(null);
        if(jLabelFoto8.getIcon()!=null){
            codigoNumero=codProdutoLista[7];
            jLabelMark8.setBorder(border2);
            ultimoMarcado=jLabelMark8;
        }        
    }//GEN-LAST:event_jLabelHover8MouseClicked

    private void jLabelHover9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover9MouseClicked
        ultimoMarcado.setBorder(null);
        if(jLabelFoto9.getIcon()!=null){
            codigoNumero=codProdutoLista[8];
            jLabelMark9.setBorder(border2);
            ultimoMarcado=jLabelMark9;
        }        
    }//GEN-LAST:event_jLabelHover9MouseClicked

    private void jLabelHover10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHover10MouseClicked
        ultimoMarcado.setBorder(null);
        if(jLabelFoto10.getIcon()!=null){
            codigoNumero=codProdutoLista[9];
            jLabelMark10.setBorder(border2);
            ultimoMarcado=jLabelMark10;
        }        
    }//GEN-LAST:event_jLabelHover10MouseClicked

    private void jLabelMark1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabelMark1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMark1FocusGained

    private void jLabelMark1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMark1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMark1MouseClicked

    private void jLabelMark1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMark1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMark1MouseEntered

    private void jLabelMark1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMark1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMark1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAdministrarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonDerecha;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonIzquierda;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto1;
    private javax.swing.JLabel jLabelFoto10;
    private javax.swing.JLabel jLabelFoto2;
    private javax.swing.JLabel jLabelFoto3;
    private javax.swing.JLabel jLabelFoto4;
    private javax.swing.JLabel jLabelFoto5;
    private javax.swing.JLabel jLabelFoto6;
    private javax.swing.JLabel jLabelFoto7;
    private javax.swing.JLabel jLabelFoto8;
    private javax.swing.JLabel jLabelFoto9;
    private javax.swing.JLabel jLabelHover1;
    private javax.swing.JLabel jLabelHover10;
    private javax.swing.JLabel jLabelHover2;
    private javax.swing.JLabel jLabelHover3;
    private javax.swing.JLabel jLabelHover4;
    private javax.swing.JLabel jLabelHover5;
    private javax.swing.JLabel jLabelHover6;
    private javax.swing.JLabel jLabelHover7;
    private javax.swing.JLabel jLabelHover8;
    private javax.swing.JLabel jLabelHover9;
    private javax.swing.JLabel jLabelMarcaFoto1;
    private javax.swing.JLabel jLabelMarcaFoto10;
    private javax.swing.JLabel jLabelMarcaFoto2;
    private javax.swing.JLabel jLabelMarcaFoto3;
    private javax.swing.JLabel jLabelMark1;
    private javax.swing.JLabel jLabelMark10;
    private javax.swing.JLabel jLabelMark2;
    private javax.swing.JLabel jLabelMark3;
    private javax.swing.JLabel jLabelMark4;
    private javax.swing.JLabel jLabelMark5;
    private javax.swing.JLabel jLabelMark6;
    private javax.swing.JLabel jLabelMark7;
    private javax.swing.JLabel jLabelMark8;
    private javax.swing.JLabel jLabelMark9;
    private javax.swing.JLabel jLabelModeloFoto1;
    private javax.swing.JLabel jLabelModeloFoto10;
    private javax.swing.JLabel jLabelModeloFoto2;
    private javax.swing.JLabel jLabelModeloFoto3;
    public static javax.swing.JPanel jPanelAdministrarProducto;
    private javax.swing.JTextField jTextFieldBuscarCoincidencia;
    // End of variables declaration//GEN-END:variables
}
