/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Conexion.ConectarBD;
import static Vista.InterLogin.nombreUsuarioVendedor;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class InterfazRegistrarVenta extends javax.swing.JFrame {

    static Connection conexion=null;
    static Statement sentencia=null;
    ConectarBD con = new ConectarBD();
    public static ArrayList<Object []> elementosTabla = new ArrayList<>();    
    private int itemDetalleVenta;    
    Date fechaActual = new Date();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
    String fechaFormateada = formatoFecha.format(fechaActual);

    public InterfazRegistrarVenta() {
        initComponents();        
        //this.setDefaultCloseOperation(1);
        this.setLocationRelativeTo(null);
        jLabelNombreUsuario.setText(nombreUsuarioVendedor);
        jTextFieldFecha.setText(fechaFormateada);
        jTextFieldFecha.setEditable(false);
        jTextFieldMarca.setEditable(false);
        jTextFieldModelo.setEditable(false);
        jTextFieldPrecio.setEditable(false);
        jTextFieldStock.setEditable(false);
        jTextFieldTotalPagar.setEditable(false);
        jButtonAgregarProducto.setEnabled(false);
        jButtonEliminarProducto.setEnabled(false);
        jButtonImprimirProducto.setEnabled(false);
        jButtonAgregarProducto.setEnabled(false);
        jTableDetalleVenta.getTableHeader().setBackground(new Color(155,184,200));
        jTableDetalleVenta.getTableHeader().setForeground(Color.white);        
        Font newHeaderFont = jTableDetalleVenta.getFont().deriveFont(Font.BOLD, 18f);
        jTableDetalleVenta.getTableHeader().setFont(newHeaderFont);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCiNit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIdProducto = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldEsnImei = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldStock = new javax.swing.JTextField();
        jTextFieldTotalPagar = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jButtonbuscarProducto = new javax.swing.JButton();
        jButtonImprimirProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDetalleVenta = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonEliminarProducto = new javax.swing.JButton();
        jButtonAgregarProducto = new javax.swing.JButton();
        jLabelAvisoCi = new javax.swing.JLabel();
        jLabelAvisoIdProducto = new javax.swing.JLabel();
        jLabelAvisoIMEI = new javax.swing.JLabel();
        jLabelAvisoNombre = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CI/NIT");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(37, 77, 116));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 705));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton backbutton.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disable backbutton.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hover backbutton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REALIZAR VENTA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 47, -1, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, -1));

        jTextFieldCiNit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldCiNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCiNitKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCiNitKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldCiNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 91, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre/Razon Social");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jTextFieldIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdProductoActionPerformed(evt);
            }
        });
        jTextFieldIdProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIdProductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIdProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdProductoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 100, -1));

        jTextFieldMarca.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 116, -1));

        jTextFieldModelo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 124, -1));

        jTextFieldEsnImei.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldEsnImei.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEsnImeiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEsnImeiKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldEsnImei, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 170, -1));

        jTextFieldPrecio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 128, -1));

        jTextFieldStock.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextFieldStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, 108, -1));

        jTextFieldTotalPagar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalPagarActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 548, 150, -1));

        jTextFieldFecha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 98, -1));

        jButtonbuscarProducto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonbuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton Buscar.png"))); // NOI18N
        jButtonbuscarProducto.setBorder(null);
        jButtonbuscarProducto.setContentAreaFilled(false);
        jButtonbuscarProducto.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disable Buscar.png"))); // NOI18N
        jButtonbuscarProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hover Buscar.png"))); // NOI18N
        jButtonbuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbuscarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonbuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, -1, -1));

        jButtonImprimirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton imprimir.png"))); // NOI18N
        jButtonImprimirProducto.setBorder(null);
        jButtonImprimirProducto.setBorderPainted(false);
        jButtonImprimirProducto.setContentAreaFilled(false);
        jButtonImprimirProducto.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disable imprimir.png"))); // NOI18N
        jButtonImprimirProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hover imprimir.png"))); // NOI18N
        jButtonImprimirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonImprimirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 620, -1, -1));

        jTableDetalleVenta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTableDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID producto", "Marca", "Modelo", "Cantidad", "ESN/IMEI", "Importe"
            }
        ));
        jTableDetalleVenta.setRowHeight(25);
        jTableDetalleVenta.setSelectionBackground(new java.awt.Color(195, 224, 229));
        jTableDetalleVenta.setShowVerticalLines(false);
        jTableDetalleVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableDetalleVentaFocusLost(evt);
            }
        });
        jTableDetalleVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDetalleVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDetalleVenta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 377, 949, 163));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CI/NIT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Id producto");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Marca");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modelo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ESN/IMEI");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Stock");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("precio");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("total a pagar");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 549, -1, -1));

        jButtonEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trash_bin 64px.png"))); // NOI18N
        jButtonEliminarProducto.setBorder(null);
        jButtonEliminarProducto.setContentAreaFilled(false);
        jButtonEliminarProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trash hover.png"))); // NOI18N
        jButtonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 146, -1, -1));

        jButtonAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add_circle_72.png"))); // NOI18N
        jButtonAgregarProducto.setBorder(null);
        jButtonAgregarProducto.setContentAreaFilled(false);
        jButtonAgregarProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add circle hover.png"))); // NOI18N
        jButtonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 146, 64, 65));

        jLabelAvisoCi.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jLabelAvisoCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 219, 180, 20));

        jLabelAvisoIdProducto.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jLabelAvisoIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 339, 180, 20));

        jLabelAvisoIMEI.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jLabelAvisoIMEI, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 339, 180, 20));

        jLabelAvisoNombre.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jLabelAvisoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 219, 180, 20));

        jLabelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(jLabelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 42, 110, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/user.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 38, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nombre usuario.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        InterLogin login=new InterLogin();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldIdProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdProductoKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){           
            try {                
                conexion=con.establecerConexion();
                PreparedStatement pst = conexion.prepareStatement("SELECT * FROM PRODUCTO WHERE codProducto ='"+jTextFieldIdProducto.getText()+"'");
                ResultSet rs = pst.executeQuery();                
                if(rs.next()){
                    //Datos consultados
                    jTextFieldMarca.setText(rs.getString("marcaProducto"));
                    jTextFieldModelo.setText(rs.getString("modeloProducto"));
                    jTextFieldPrecio.setText(rs.getString("precioProducto"));
                    int Stock=Integer.parseInt(rs.getString("stockProducto"));
                    if(elementosTabla.isEmpty()!=true){
                        for(int i=0; i<elementosTabla.size();i++){
                            Object [] fila =elementosTabla.get(i);
                            String id=(String)fila[0];
                            if(id.contentEquals(jTextFieldIdProducto.getText())){
                                Stock--;
                            }
                        }                        
                    }
                    jTextFieldStock.setText(Stock+"");
                }else{
                    jTextFieldMarca.setText("");
                    jTextFieldModelo.setText("");
                    jTextFieldPrecio.setText("");
                    jTextFieldStock.setText("");
                    JOptionPane.showMessageDialog(null, "Id Producto inexistente");
                }                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "¡Error al cargar!");
                System.out.println("Error al cargar foto: " + e);
            }
                               
        }
    }//GEN-LAST:event_jTextFieldIdProductoKeyPressed

    private void jButtonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarProductoActionPerformed
        int sumaImporte=0;
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int x, int y){
                return false;
            }
        };
        //se reduce la cantidad del stock
        int reducirCantidad=Integer.parseInt(jTextFieldStock.getText());
        reducirCantidad--;
        jTextFieldStock.setText(reducirCantidad+"");
        if (reducirCantidad==0){
            jButtonAgregarProducto.setEnabled(false);
        }
        
        modelo.addColumn("ID Producto");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Cantidad");
        modelo.addColumn("ESN/IMEI");
        modelo.addColumn("Importe");
        
        Object [] lista = {jTextFieldIdProducto.getText(), jTextFieldModelo.getText(), jTextFieldModelo.getText(),1,jTextFieldEsnImei.getText(),jTextFieldPrecio.getText()};
        elementosTabla.add(lista);
        for(int i=0; i<elementosTabla.size();i++){
            Object [] a =elementosTabla.get(i);
            modelo.addRow(a);
        }        
        jTableDetalleVenta.setModel(modelo);
        for(int i=0; i<elementosTabla.size();i++){
            Object [] fila =elementosTabla.get(i);
            String elemento = (String)fila[5];
            sumaImporte=sumaImporte+Integer.parseInt(elemento);            
        }
        String text=sumaImporte+"";
        jTextFieldTotalPagar.setText(text);
        jButtonEliminarProducto.setEnabled(false);
        jButtonAgregarProducto.setEnabled(false);
        jTextFieldEsnImei.setText("");
        habilitarBotonImprimir();
    }//GEN-LAST:event_jButtonAgregarProductoActionPerformed

    private void jTableDetalleVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDetalleVentaMouseClicked
        itemDetalleVenta=jTableDetalleVenta.rowAtPoint(evt.getPoint());
        if (itemDetalleVenta>=0){
            jButtonEliminarProducto.setEnabled(true);
        }
        
    }//GEN-LAST:event_jTableDetalleVentaMouseClicked

    private void jButtonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarProductoActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar el producto?", "Confirmación de eliminación", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            int sumaImporte=0;
            DefaultTableModel modelo = new DefaultTableModel(){};
            
            modelo.addColumn("ID Producto");
            modelo.addColumn("Marca");
            modelo.addColumn("Modelo");
            modelo.addColumn("Cantidad");
            modelo.addColumn("ESN/IMEI");
            modelo.addColumn("Importe");

            elementosTabla.remove(itemDetalleVenta);
            for(int i=0; i<elementosTabla.size();i++){
                Object [] a =elementosTabla.get(i);
                modelo.addRow(a);
            }
            for(int i=0; i<elementosTabla.size();i++){
                Object [] fila =elementosTabla.get(i);
                String elemento = (String)fila[5];
                sumaImporte=sumaImporte+Integer.parseInt(elemento);            
            }
            String text=sumaImporte+"";
            jTextFieldTotalPagar.setText(text);
            jTableDetalleVenta.setModel(modelo);
            jButtonEliminarProducto.setEnabled(false);
            habilitarBotonImprimir();
        }
    }//GEN-LAST:event_jButtonEliminarProductoActionPerformed

    private void jTextFieldIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdProductoActionPerformed

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    private void jTableDetalleVentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableDetalleVentaFocusLost
    }//GEN-LAST:event_jTableDetalleVentaFocusLost

    private void jButtonbuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbuscarProductoActionPerformed
        InterfazBuscarProducto buscarPro=new InterfazBuscarProducto();
        buscarPro.setVisible(true);
        buscarPro.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonbuscarProductoActionPerformed

    private void jTextFieldIdProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdProductoKeyTyped
        validacionNumero(evt);
        avisoLongitudMax(jTextFieldIdProducto,3,evt);        
    }//GEN-LAST:event_jTextFieldIdProductoKeyTyped

    private void jTextFieldEsnImeiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEsnImeiKeyTyped
        validacionNumero(evt);
        avisoLongitudMax(jTextFieldEsnImei,16,evt);
    }//GEN-LAST:event_jTextFieldEsnImeiKeyTyped

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        validacionCaracteresLetras(evt);
        avisoLongitudMax(jTextFieldNombre,20,evt);
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldCiNitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCiNitKeyTyped
        validacionNumero(evt);
        avisoLongitudMax(jTextFieldCiNit,9,evt);
    }//GEN-LAST:event_jTextFieldCiNitKeyTyped

    private void jTextFieldCiNitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCiNitKeyReleased
        avisoLongitudMin(jTextFieldCiNit,jLabelAvisoCi,7);
        habilitarBotonImprimir();
    }//GEN-LAST:event_jTextFieldCiNitKeyReleased

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased
        avisoLongitudMin(jTextFieldNombre,jLabelAvisoNombre,3);
        habilitarBotonImprimir();
    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    private void jTextFieldIdProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdProductoKeyReleased
        avisoLongitudMin(jTextFieldIdProducto,jLabelAvisoIdProducto,1);
        habilitarBotonAgregar();
    }//GEN-LAST:event_jTextFieldIdProductoKeyReleased

    private void jTextFieldEsnImeiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEsnImeiKeyReleased
        avisoLongitudMin(jTextFieldEsnImei,jLabelAvisoIMEI,15);
        habilitarBotonAgregarImei();
    }//GEN-LAST:event_jTextFieldEsnImeiKeyReleased

    private void jButtonImprimirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImprimirProductoActionPerformed

    private void jTextFieldTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistrarVenta().setVisible(true);
            }
        });
    }
    public void validacionNumero(java.awt.event.KeyEvent evento){
        if((evento.getKeyChar()<48 || evento.getKeyChar()>57)&&
            evento.getKeyChar()!=8&&evento.getKeyChar()!=10){
            evento.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten Números");
        }
    }
    public void validacionCaracteresLetras(java.awt.event.KeyEvent evento){
        if((evento.getKeyChar()<97 || evento.getKeyChar()>122)&& //a-z
        (evento.getKeyChar()<65 || evento.getKeyChar()>90)&& //A-Z
        evento.getKeyChar()!=209&&evento.getKeyChar()!=241&&
        evento.getKeyChar()!=8&&evento.getKeyChar()!=32&&
        evento.getKeyChar()!=225&&evento.getKeyChar()!=233&&
        evento.getKeyChar()!=237&&evento.getKeyChar()!=243&&
        evento.getKeyChar()!=250&&evento.getKeyChar()!=193&&
        evento.getKeyChar()!=201&&evento.getKeyChar()!=205&&
        evento.getKeyChar()!=211&&evento.getKeyChar()!=218){
            evento.consume();
            JOptionPane.showMessageDialog(null, "No se permiten Caracteres Especiales");
        }
    }
    public void avisoLongitudMax (JTextField a, int maximo,KeyEvent z){

        if(a.getText().length()>=maximo){
            z.consume();
            Toolkit.getDefaultToolkit().beep();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "LLEGO AL LIMITE PERMITIDO");
        }
    }
    
    public void avisoLongitudMin (JTextField a,JLabel b, int cantidad){
        if(a.getText().isEmpty()){
            b.setText("Campo Obligatorio");
        }else {
            if (a.getText().length()<=cantidad-1){
                b.setText("Se requiere de "+ cantidad +" caracteres");  
            }else{
                b.setText("");}
        }
    }
    public boolean valorRepetidoImei(JTextField a,ArrayList<Object []> b){
        if(b.isEmpty()!=true){
            for(int i=0; i<b.size();i++){
                Object [] fila =b.get(i);
                String Imei=(String)fila[4];
                if(Imei.contentEquals(a.getText())){
                    jLabelAvisoIMEI.setText("Codigo ESN/IMEI repetido");
                    return true;
                }else{
                    return false;
                }
            }
            return false;
        }else{
            return false;
        }
    }
    
    public void habilitarBotonImprimir(){
        if(jTextFieldNombre.getText().isEmpty()
                || jTextFieldCiNit.getText().isEmpty()
                || elementosTabla.isEmpty()                
                || jTextFieldNombre.getText().length()<3
                || jTextFieldCiNit.getText().length()<7){
            jButtonImprimirProducto.setEnabled(false);
        }else{
            jButtonImprimirProducto.setEnabled(true);
        }
    }
    
    public void habilitarBotonAgregar(){
        if(jTextFieldIdProducto.getText().isEmpty()
                || jTextFieldEsnImei.getText().isEmpty()
                || jTextFieldMarca.getText().isEmpty()
                || jTextFieldStock.getText().contentEquals("0")
                || jTextFieldIdProducto.getText().length()<1
                || jTextFieldEsnImei.getText().length()<15){
            jButtonAgregarProducto.setEnabled(false);
        }else{
            if (jTextFieldStock.getText().equals("")){
                jButtonAgregarProducto.setEnabled(false);
            }else{
                if (Integer.parseInt(jTextFieldStock.getText())==0){
                    jButtonAgregarProducto.setEnabled(false);
                }else{
                    jButtonAgregarProducto.setEnabled(true);
                }
            }
        }
    }
    public void habilitarBotonAgregarImei(){
        if(jTextFieldIdProducto.getText().isEmpty()
                || jTextFieldEsnImei.getText().isEmpty()
                || jTextFieldMarca.getText().isEmpty()
                || jTextFieldStock.getText().contentEquals("0")
                || jTextFieldIdProducto.getText().length()<1
                || jTextFieldEsnImei.getText().length()<15){
            jButtonAgregarProducto.setEnabled(false);
        }else{
            if (jTextFieldStock.getText().equals("")){
                jButtonAgregarProducto.setEnabled(false);
            }else{
                if (valorRepetidoImei(jTextFieldEsnImei,elementosTabla)){
                    jButtonAgregarProducto.setEnabled(false);
                }else{
                    if (Integer.parseInt(jTextFieldStock.getText())==0){
                        jButtonAgregarProducto.setEnabled(false);
                    }else{
                        jButtonAgregarProducto.setEnabled(true);
                    }
                }                
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregarProducto;
    private javax.swing.JButton jButtonEliminarProducto;
    private javax.swing.JButton jButtonImprimirProducto;
    private javax.swing.JButton jButtonbuscarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAvisoCi;
    private javax.swing.JLabel jLabelAvisoIMEI;
    private javax.swing.JLabel jLabelAvisoIdProducto;
    private javax.swing.JLabel jLabelAvisoNombre;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDetalleVenta;
    private javax.swing.JTextField jTextFieldCiNit;
    public static javax.swing.JTextField jTextFieldEsnImei;
    private javax.swing.JTextField jTextFieldFecha;
    public static javax.swing.JTextField jTextFieldIdProducto;
    public static javax.swing.JTextField jTextFieldMarca;
    public static javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNombre;
    public static javax.swing.JTextField jTextFieldPrecio;
    public static javax.swing.JTextField jTextFieldStock;
    private javax.swing.JTextField jTextFieldTotalPagar;
    // End of variables declaration//GEN-END:variables
}
