/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Conexion.ConectarBD;
import static Vista.InterfazEliminarProducto.conexion;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class InterfazAdministrarProducto extends javax.swing.JFrame {
    static Connection conexion=null;
    ConectarBD con = new ConectarBD();
    public javax.swing.JLabel jLabelFoto;
    public javax.swing.JLabel jLabelMarca;
    public javax.swing.JLabel jLabelModelo;
    int [] codProdutoLista=new int [10];
    public static int codigoNumero;
    /**
     * Creates new form InterfazAdministrarProducto
     */
    public InterfazAdministrarProducto() {
        initComponents();
        
        int i=0;
        int j=0;
        
        
        try {
                
                conexion=con.establecerConexion();
                PreparedStatement pst = conexion.prepareStatement("SELECT * FROM PRODUCTO ORDER BY marcaProducto ASC");
                ResultSet rs = pst.executeQuery();
                
                while(rs.next()){
                    jLabelFoto=(JLabel) jPanel1.getComponent(8+i);
                    jLabelMarca=(JLabel) jPanel1.getComponent(9+i);
                    jLabelModelo=(JLabel) jPanel1.getComponent(10+i);
                    i=i+3;
                    codProdutoLista[j]=rs.getInt("codProducto");
                    j++;
                    jLabelMarca.setText(rs.getString("marcaProducto"));
                    jLabelModelo.setText(rs.getString("modeloProducto"));
                    
                    Blob blob = rs.getBlob("fotoProducto");
                    //pasar el binario a imagen
                    byte[] data = blob.getBytes(1, (int) blob.length());
                    //lee la imagen
                    BufferedImage img = null;
                    try {
                        img = ImageIO.read(new ByteArrayInputStream(data));
                    } catch (IOException e) {
                        Logger.getLogger(InterfazEliminarProducto.class.getName()).log(Level.SEVERE, null, e);
                    }                    
                    ImageIcon icono = new ImageIcon(img);
                    Icon imagen = new ImageIcon(icono.getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT));
                    jLabelFoto.setIcon(imagen);
                    
                }
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "¡Error al cargar!");
                System.out.println("Error al cargar foto: " + e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBuscarCoincidencia = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabelFoto1 = new javax.swing.JLabel();
        jLabelMarcaFoto1 = new javax.swing.JLabel();
        jLabelModeloFoto1 = new javax.swing.JLabel();
        jLabelFoto2 = new javax.swing.JLabel();
        jLabelMarcaFoto2 = new javax.swing.JLabel();
        jLabelModeloFoto2 = new javax.swing.JLabel();
        jLabelFoto3 = new javax.swing.JLabel();
        jLabelMarcaFoto3 = new javax.swing.JLabel();
        jLabelModeloFoto3 = new javax.swing.JLabel();
        jLabelFoto4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelFoto5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelFoto6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelFoto7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelFoto8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelFoto9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelFoto10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(37, 77, 116));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMINISTRAR PRODUCTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jTextFieldBuscarCoincidencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextFieldBuscarCoincidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarCoincidenciaActionPerformed(evt);
            }
        });
        jTextFieldBuscarCoincidencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarCoincidenciaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarCoincidenciaKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldBuscarCoincidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 260, 30));

        jButtonBuscar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
        });
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jButtonBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonBuscarKeyPressed(evt);
            }
        });
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de Producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 210, -1));

        jButtonEditar.setBackground(new java.awt.Color(95, 143, 169));
        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, -1, 30));

        jButtonEliminar.setBackground(new java.awt.Color(95, 143, 169));
        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, -1, 30));

        jButtonRegistrar.setBackground(new java.awt.Color(95, 143, 169));
        jButtonRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 610, -1, 30));

        jButtonHome.setText("home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabelFoto1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto1.setText("foto1");
        jLabelFoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelFoto1.setName(""); // NOI18N
        jLabelFoto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFoto1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 140, 110));

        jLabelMarcaFoto1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMarcaFoto1.setText("jLabel3");
        jPanel1.add(jLabelMarcaFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 110, -1));

        jLabelModeloFoto1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModeloFoto1.setText("jLabel4");
        jPanel1.add(jLabelModeloFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        jLabelFoto2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto2.setText("foto2");
        jLabelFoto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelFoto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFoto2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 140, 110));

        jLabelMarcaFoto2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMarcaFoto2.setText("jLabel6");
        jPanel1.add(jLabelMarcaFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        jLabelModeloFoto2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModeloFoto2.setText("jLabel5");
        jPanel1.add(jLabelModeloFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jLabelFoto3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto3.setText("foto3");
        jLabelFoto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelFoto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFoto3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelFoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 140, 110));

        jLabelMarcaFoto3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMarcaFoto3.setText("jLabel3");
        jPanel1.add(jLabelMarcaFoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        jLabelModeloFoto3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModeloFoto3.setText("jLabel4");
        jPanel1.add(jLabelModeloFoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        jLabelFoto4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto4.setText("foto4");
        jLabelFoto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabelFoto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 140, 110));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        jLabelFoto5.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFoto5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto5.setText("foto5");
        jPanel1.add(jLabelFoto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 140, 110));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, -1, -1));

        jLabelFoto6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto6.setText("foto6");
        jLabelFoto6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabelFoto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 140, 110));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, -1, -1));

        jLabelFoto7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto7.setText("foto7");
        jLabelFoto7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabelFoto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 140, 110));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, -1, -1));

        jLabelFoto8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto8.setText("foto8");
        jLabelFoto8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabelFoto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 140, 110));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, -1, -1));

        jLabelFoto9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto9.setText("foto9");
        jLabelFoto9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabelFoto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 140, 110));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, -1, -1));

        jLabelFoto10.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto10.setText("foto10");
        jLabelFoto10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabelFoto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 140, 110));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarCoincidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarCoincidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarCoincidenciaActionPerformed

    private void jTextFieldBuscarCoincidenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarCoincidenciaKeyPressed

    }//GEN-LAST:event_jTextFieldBuscarCoincidenciaKeyPressed

    private void jTextFieldBuscarCoincidenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarCoincidenciaKeyTyped

    }//GEN-LAST:event_jTextFieldBuscarCoincidenciaKeyTyped

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked

    }//GEN-LAST:event_jButtonBuscarMouseClicked

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonBuscarKeyPressed

    }//GEN-LAST:event_jButtonBuscarKeyPressed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        InterfazEditarProducto editarPro=new InterfazEditarProducto();
        editarPro.setVisible(true);
        editarPro.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        InterfazEliminarProducto eliminarPro=new InterfazEliminarProducto();
        eliminarPro.setVisible(true);
        eliminarPro.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        InterfazRegistrarProducto registrarPro=new InterfazRegistrarProducto();
        registrarPro.setVisible(true);
        registrarPro.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jLabelFoto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFoto1MouseClicked
        codigoNumero=codProdutoLista[0];
    }//GEN-LAST:event_jLabelFoto1MouseClicked

    private void jLabelFoto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFoto2MouseClicked
        codigoNumero=codProdutoLista[1];
    }//GEN-LAST:event_jLabelFoto2MouseClicked

    private void jLabelFoto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFoto3MouseClicked
        codigoNumero=codProdutoLista[2];
    }//GEN-LAST:event_jLabelFoto3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAdministrarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto1;
    private javax.swing.JLabel jLabelFoto10;
    private javax.swing.JLabel jLabelFoto2;
    private javax.swing.JLabel jLabelFoto3;
    private javax.swing.JLabel jLabelFoto4;
    private javax.swing.JLabel jLabelFoto5;
    private javax.swing.JLabel jLabelFoto6;
    private javax.swing.JLabel jLabelFoto7;
    private javax.swing.JLabel jLabelFoto8;
    private javax.swing.JLabel jLabelFoto9;
    private javax.swing.JLabel jLabelMarcaFoto1;
    private javax.swing.JLabel jLabelMarcaFoto2;
    private javax.swing.JLabel jLabelMarcaFoto3;
    private javax.swing.JLabel jLabelModeloFoto1;
    private javax.swing.JLabel jLabelModeloFoto2;
    private javax.swing.JLabel jLabelModeloFoto3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBuscarCoincidencia;
    // End of variables declaration//GEN-END:variables
}
